### ISSUE TITLE
Lors de l'inclusion aucun module n'apparait

### ISSUE THREAD

**Issue by zoic21** [jeedom/plugin-openzwave#10]
Lors de l'inclusion d'un module tout semble bien se passer mais le module n'apparait et le réseaux est très lent avec aucune remonté d'information.

Voir @sarakha63

**Comment by sarakha63** [comment]
Il semblerait que pendant le mode inclusion/exclusion des events s'empilent dans la queue bloquant ou perturbant l'inclusion ou l'exclusion. Cela se conforte avec le fait que 'linclsuion avec clé debranché se passe bien

**Comment by sarakha63** [comment]
Généralement soit l'interview se fait pas soit il se fait de manière completement incomplete. Soit complete mais de manière très regulière le retour d'état est perdu sur l'ensemble du réseau
