### ISSUE TITLE
Le répertoire .git fait partie de l'archive livrée dans le market 

### ISSUE THREAD

**Issue by cazeaux** [jeedom/plugin-openzwave#18]
Juste pour signaler que le répertoire .git fait partie de l'archive livrée dans le plugin stable disponible.
Pas un gros problème en soi, mais ça peut rapidement devenir un dossier volumineux ...

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour, j'ai fait les correction il ne sera plus dans les prochaines version
