### ISSUE TITLE
Jeedom: unrecognized service

### ISSUE THREAD

**Issue by sguilly** [jeedom/plugin-openzwave#19]
Bonjour,

Je viens d'installer Jeedom en mode docker en suivant la documentation.

Le container est lancé avec 'docker run --name jeedom -p 22 -p 80 -p 9001 --device=/dev/ttyACM0:/dev/ttyACM0 cquad/jeedom'

L'installation du plugin openzwave en mode beta s'est bien passé mise à part que durant l'installation d'openzwave, je trouve dans les logs : Jeedom: unrecognized service

Le plugin trouve bien ma clé USB et le bouton inclusion fonctionne correctement.

Dans options avancés, le bouton 'console' me permet de voir qu'openzwave fonctionne correctement et communique avec des devices zwave.

Par contre, j'ai le statut Retour Local et Retour distant qui restent à NOK.

Et je ne vois rien dans 'Mes équipements Z-Wave'. Cette page affiche uniquement les boutons Inclusion et Exclusion (il me semble qu'il devrait avoir des boutons à droite).

Je ne sais plus où chercher...

Merci

Stéphane

**Comment by zoic21** [comment]
Bonjour,
Ton soucis viens d'une mauvaise configuration réseaux de jeedom (a faire dans Général -> Administration -> Configurationà

**Comment by PalmBox** [comment]
j'ai le même souci, et je ne vois pas ce que je dois changer dans la configuration. Zoic, peux-tu préciser stp ? Merci

**Comment by sarakha63** [comment]
Les boutons en plus ne se voient comme mode expert. Concernant le retour locla il faut sassurer de sa config reseau dans administration/config/comfig reseau

**Comment by PalmBox** [comment]
Bon, en fait, j'ai trouvé tout seul hier soir. Voici ce qu'il faut faire si les Retour Local et Retour Distant sont à NOK : 
- Aller dans Général > Administration > Configuration
- Aller dans la section Configuration réseaux
- Configurer Accès interne et Accès externe
