### ISSUE TITLE
Nombre d'associations visible ne correspond pas 

### ISSUE THREAD

**Issue by nechry** [jeedom/plugin-openzwave#27]
en référence au post:
https://www.jeedom.fr/forum/viewtopic.php?f=87&t=11885&p=235799#p235799

certaines associations ne sont pas affichées.

a valider / tester

**Comment by fschrot** [comment]
Avez vous des nouvelles de ce ticket ? je n'ai pas tous mes modules qui apparaissent... du coup je ne sais plus ce que j'ai déjà ajouté :)
Merci

**Comment by nechry** [comment]
je n'ai pas encore regardé. désolé. j'essais de faire cette semaine.

**Comment by nechry** [comment]
impossible a reproduire.
