### ISSUE TITLE
Ajout du support Popp Wall Plug Switch Outdoor

### ISSUE THREAD

**Issue by zoic21** [jeedom/plugin-openzwave#32]

**Comment by zofiel** [comment]
Manual:
https://docs.google.com/viewer?url=http%3A%2F%2Fwww.popp.eu%2Fwp-content%2Fuploads%2F2016%2F01%2FManual_IP44_POPP_En.pdf

**Comment by nechry** [comment]
https://github.com/jeedom/plugin-openzwave/commit/bd8f4cbe1e12e66721b2fb37cc05c14b54d7f65c
