### ISSUE TITLE
Noms des modules dans table routage+santé mélange id avec controlleurs multiples

### ISSUE THREAD

**Issue by spyjo** [jeedom/plugin-openzwave#35]
Hello,

Actuellement dans la version stable du plugin (c'est peut-etre déjà corrigé dans la beta...), quand on tourne avec plusieurs controlleurs zwave (1 local et 1 distant), les noms se mélangent dans les tables de routage et de santé pour les même id.
C'est à dire que si le controlleur zwave 1 a un module qui à l'id 2, et que le controlleur zwave 2 a aussi un module qui a l'id 2, le nom affiché dans les tableaux n'est pas bon quand on regarde pour le second controlleur, ça affiche le nom du module du premier controlleur.
Par contre le reste des informations correspond bien au bon module, il me semble qu'il n'y a que le nom qui pose soucis.

**Comment by KiwiHC16** [comment]
Hello,
Je confirme que j'avais ce problème en Jeedom 1.2xx mais n'est plus présent en Jeedom 2.0.1 (Zwave du 2016-02-18 13:34:01).

**Comment by spyjo** [comment]
Ok je cloture dans ce cas, lors de ma migration en 2.0 j'en ai profité pour repasser sur un seul dongle usb au lieu de deux donc je ne peux pas voir si j'ai toujours le soucis.
