### ISSUE TITLE
Z-Stick sans voisine (Neighbors)

### ISSUE THREAD

**Issue by KiwiHC16** [jeedom/plugin-openzwave#37]
Hello,
Sur le master et sur l'esclave, dans la page "Santé zwave", le statut du stick reste à "Neighbors" et la liste des voisines pour le stick zwave est vide. Tout semble fonctionner correctement du point de vue zwave. Dans le résumé de Z-Stick on a "La liste des noeuds voisin n'est pas encore disponible."
Reste vide meme après des demandes de "mise a jour des noeud voisins", "soigner le noeud",... 
Jeedom 2.0.1 et Zwave: Version du :  2016-02-18 13:34:01 et complete fresh installation

**Comment by nechry** [comment]
stop jeedom, débranche le dongle 1 minute , rebranche et redémarre.

**Comment by KiwiHC16** [comment]
Fait plusieurs fois. Je n'avais pas ce soucis en Jeedom 1.2xx. J'ai ce soucis depuis que je suis sous jeedom 2.0.x.
Arret/redemarrage, Arret coupure électricité, Hard reset du Stick, Soft reset du Stick, rien ni fait. ;-)

**Comment by nechry** [comment]
il faut éventuellement essayer via open-zwave-control-panel
https://github.com/OpenZWave/open-zwave-control-panel

si le même résultat

il est disponible sous docker pour simplifier l'installation:
https://github.com/OpenZWave/DockerImages

**Comment by KiwiHC16** [comment]
Merci pour cette idée.

J’ai toujours utilisé open-zwave-control-panel avec une sur-couche php à ma sauce jusqu’a il y a un mois avec le passage sous jeedom.
Je n’ai jamais rencontré ce problème avec control-panel. 
J’avais installé Jeedom en version 1.212.x et je n’avais pas non plus ce problème.
Ce problème est apparu avec Jeedom V2.0.1 et la mise a jour de open zwave associé (installation from scratch, no upgrade).
J’ai le meme problème sur le maitre et sur l’esclave.

Je vais faire une série de test avec jeedom 1.2xxx et control-panel des que je trouve un peu de temps.

Meme si les voisines ne sont pas rapportées par le dongle, le système fonctionne correctement ...

**Comment by KiwiHC16** [comment]
Bonsoir, je viens de faire une install de open-zwave et open-zwave-control-panel depuis git en prenant les dernières versions et j'ai le même soucis. Le contrôleur ne remonte pas ses voisines.

^[[39m^[[39m2016-03-03 20:53:30.371 Info, Node001, Sending (Command) message (Callback ID=0x00, Expected Reply=0x80) - Get Routing Info (Node=1): 0x01, 0x07, 0x00, 0x80, 0x01, 0x00, 0x00, 0x03, 0x7a
^[[39m^[[34m2016-03-03 20:53:30.378 Detail, Node001,   Received: 0x01, 0x20, 0x01, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x5e
^[[39m^[[34m2016-03-03 20:53:30.378 Detail,
^[[39m^[[39m2016-03-03 20:53:30.378 Info, Node001, Received reply to FUNC_ID_ZW_GET_ROUTING_INFO
^[[39m^[[39m2016-03-03 20:53:30.378 Info, Node001,     Neighbors of this node are:
^[[39m^[[39m2016-03-03 20:53:30.378 Info, Node001,  (none reported)
^[[39m^[[34m2016-03-03 20:53:30.378 Detail,   Expected reply was received
^[[39m^[[34m2016-03-03 20:53:30.378 Detail,   Message transaction complete
^[[39m^[[34m2016-03-03 20:53:30.378 Detail,
^[[39m^[[34m2016-03-03 20:53:30.378 Detail, Node001, Removing current message

Le problème est dans la pile openzwave...

**Comment by nechry** [comment]
chez moi soigner le contrôleur ne fonctionne jamais. mais j'avais compris que c'était pour tout les modules.
tu peux éventuellement faire un issue dans la lib avec ton log

**Comment by KiwiHC16** [comment]
Tres bizarre: J'ai deux sticks Zwave qui ne se comportent pas de la même manière.
Je viens de faire une fresh install sur une VM pour avoir le meme soft et voir si je retrouve les différences en testant les deux sticks l'un après l'autre.
Le premiers ne me retourne pas les voisines et le second oui dans le log openzwave.log.
Dans la page web jeedom-Plugin-zwave-sante, le premier apparait dans la liste et pas le second.
Donc ce n'est pas jeedom ou openzwave qui font cette difference mais très probablement le stick.
Peut être devrais je reinstaller le firmware sur celui qui ne remonte pas ses voisines mais je vais perdre toutes la config ;-(
Ou alors il me faut transférer la config du stick en défaut vers un autre, puis mettre à jour le firmware ? Est ce que quelqu'un a deja fait cette manip ? Dois je passer par un "Créer un nouveau noeud primaire" associé à un "Receive Configuration" ?
