### ISSUE TITLE
Impossible de renommer un nœud (Z-Wave esclave)

### ISSUE THREAD

**Issue by dough29** [jeedom/plugin-openzwave#51]
Bonjour,

Malgré un sujet ouvert sur le forum - https://www.jeedom.com/forum/viewtopic.php?f=87&t=18164 - j'ai un problème qui persiste sur mon installation.

Contexte :
- Jeedom maître sur Docker
- Jeedom esclave sur Raspberry Pi avec carte RaZberry

J'essaie de renommer un équipement, le retour sur la page m'indique "Sauvegarde effectuée avec succès" alors que rien n'a été sauvé.

Je ne trouve rien dans les logs même en niveau debug.

**Comment by zoic21** [comment]
Bonjour,
C'est un soucis connu de jeedom sur docker, nous ne comprenons pas d'ou il vient mais cherchons activement. Le soucis ne vient pas du plugin openzwave je ferme donc.
